package com.alok.ecsystem.core;

/**
 * Interface to define user and control interface for an floor control board.
 * This interface is use by client of system to interact with individual floor board. 
 * This also use by {@link ElevatorSystemControl} to get floor requests.
 * 
 * @author Alok Kushwah (akushwah)
 */
public interface FloorControlInterface {
	
	/**
	 * Event type generated by floor board
	 */
	public enum FLOOR_EVENT{BUTTON_PRESSED, BUTTON_OFF, ELEVATOR_ARRIVED, ELEVATOR_LEFT};

	/**
	 * Unique id
	 * @return int
	 */
	public int getId();
	
	/**
	 * Should be called when button is pressed to call elevator.
	 * @param requsted - boolean true if button is pressed or false to reset.
	 */
	public void setElevatorRequest(boolean requsted);
	
	/**
	 * Return status of request 
	 * @return boolean - true if elevator request is pending otherwise false.
	 */
	public boolean getElevatorRequest();
	
	/**
	 * Returns Elevator interface in case elevator is serving the floor. 
	 * @return {@link ElevatorControlInterface}
	 */
	public ElevatorControlInterface getElevatorControl();
	
	/**
	 * This method is called by elevator to announce elevator arrived on request.
	 * @param elevator
	 */
	public void elevatorArrived(ElevatorControlInterface elevator);
	
}
